# Site settings
title: Divest DU
author: Lucio Franco
email: divestdu@gmail.com
url: "http://divestdu.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
#  sass_dir:          _scss
  style:            :compressed
