# Site settings
title: Divest DU
author: Lucio Franco
email: lucio.franco@du.edu
url: "https://LucioFranco.github.io/divest-du" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
#  sass_dir:          _scss
  style:            :compressed
